"use client"

import { useState } from "react"
import { Card, CardDescription, CardHeader, CardContent } from "./ui/card"
import { Button } from "./ui/button"
import { Input } from "./ui/input"

export default function ProvablyFairComponent() {
  const [serverSeed, setServerSeed] = useState("")
  const [clientSeed, setClientSeed] = useState("")
  const [nonce, setNonce] = useState("")
  const [result, setResult] = useState<string | null>(null)

  const verifyResult = () => {
    // You will replace this with your API call to random.org
    if (!serverSeed || !clientSeed || !nonce) {
      alert("Please fill all fields")
      return
    }

    // Temporary fake result for UI preview
    const randomValue = Math.floor(Math.random() * 100)
    setResult(randomValue >= 50 ? "HEADS" : "TAILS")
  }

  return (
    <div className="max-w-4xl mx-auto p-6 space-y-6">
      <Card className="border border-border bg-card">
        <CardHeader>
          <h1 className="text-2xl font-bold">Provably Fair</h1>
          <CardDescription>
            Every coin flip is generated using a combination of:
            <br />
            • Server Seed (generated by us)
            <br />
            • Client Seed (generated by you)
            <br />
            • Nonce (incremented per game)
          </CardDescription>
        </CardHeader>

        <CardContent className="space-y-4">

          {/* Server Seed */}
          <div>
            <label className="text-sm text-muted-foreground">
              Server Seed
            </label>
            <Input
              value={serverSeed}
              onChange={(e) => setServerSeed(e.target.value)}
              placeholder="Enter revealed server seed"
            />
          </div>

          {/* Client Seed */}
          <div>
            <label className="text-sm text-muted-foreground">
              Client Seed
            </label>
            <Input
              value={clientSeed}
              onChange={(e) => setClientSeed(e.target.value)}
              placeholder="Enter client seed"
            />
          </div>

          {/* Nonce */}
          <div>
            <label className="text-sm text-muted-foreground">
              Nonce
            </label>
            <Input
              value={nonce}
              onChange={(e) => setNonce(e.target.value)}
              placeholder="Enter nonce"
              type="number"
            />
          </div>

          <Button className="w-full" onClick={verifyResult}>
            Verify Result
          </Button>

          {result && (
            <div className="text-center mt-6">
              <p className="text-muted-foreground">Result</p>
              <p
                className={`text-3xl font-bold ${
                  result === "HEADS"
                    ? "text-green-500"
                    : "text-red-500"
                }`}
              >
                {result}
              </p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* How It Works Section */}
      <Card className="border border-border bg-card">
        <CardHeader>
          <h2 className="text-xl font-semibold">How It Works</h2>
        </CardHeader>
        <CardContent className="text-sm text-muted-foreground space-y-2">
          <p>
            1️⃣ Before the game starts, we generate a secret Server Seed.
          </p>
          <p>
            2️⃣ The Server Seed hash is shown to you so it cannot be changed.
          </p>
          <p>
            3️⃣ When the game finishes, the full Server Seed is revealed.
          </p>
          <p>
            4️⃣ Using the Server Seed + Client Seed + Nonce, the final
            coin result is generated using random.org.
          </p>
          <p>
            5️⃣ You can verify the result here anytime.
          </p>
        </CardContent>
      </Card>
    </div>
  )
}
